In [1]:
import os
os.chdir('..')
from bcmout.Sphere import Sphere
from bcmout.MeasureSpace import MeasureSpace
import torch
import numpy as np
import scipy

def closure_functional (weights, supports):
    """Define a functional representing how close to being closed the measure is"""
    vec = np.sum(weights[0]*supports,0)
    return np.linalg.norm(vec)**2

def split_measure (measure):
    weights = measure.split((1,measure.shape[1]-1),1)[0].numpy()
    supports = measure.split((1,measure.shape[1]-1),1)[1].numpy()
    return [weights,supports]
        
S = Sphere(1)
MonS = MeasureSpace(S,1,"WFR",True)
print(MonS)
print(MonS._metric)
e = MonS.random(1,6,1)
k = split_measure(e[0])
weights = k[0]
supports = k[1]
print(weights*supports)
print(np.sum(weights*supports,0))
print(np.linalg.norm(np.sum(weights*supports,0)))
scipy.optimize.minimize(closure_functional, weights, method='BFGS', args=supports)

[[ 0.12956925  0.10533556  0.12845385  0.07287787  0.02804702]
 [-0.34333274 -0.7983009   0.4375293   0.36028683  0.8123364 ]
 [-0.51589936 -0.13880444  0.48082227  0.51037425  0.09231213]]
[-0.72966284 -0.8317698   1.0468054   0.94353896  0.93269557]
2.0199597


C:\Users\Dylan\AppData\Local\Temp\ipykernel_18980\1059564851.py:30: DeprecationWarning: Use of `minimize` with `x0.ndim != 1` is deprecated. Currently, singleton dimensions will be removed from `x0`, but an error will be raised in SciPy 1.11.0.
  scipy.optimize.minimize(closure_functional, weights, method='BFGS', args=supports)


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 5.294218893941709e-16
        x: [-1.449e-08  8.233e-01 -5.676e-01]
      nit: 3
      jac: [-3.550e-08  0.000e+00  0.000e+00]
 hess_inv: [[ 3.148e-01  0.000e+00  0.000e+00]
            [ 0.000e+00  1.000e+00  0.000e+00]
            [ 0.000e+00  0.000e+00  1.000e+00]]
     nfev: 20
     njev: 5