In [1]:
import os
os.chdir('..')
from bcmout.Sphere import Sphere
from bcmout.MeasureSpace import MeasureSpace
import torch
import numpy as np
import scipy

def closure_functional (weights, supports):
    """Define a functional representing how close to being closed the measure is"""
    vec = np.sum(weights[0]*supports,0)
    return np.inner(vec,vec)

def split_measure (measure):
    weights = measure.split((1,measure.shape[0]-1),0)[0].numpy()
    supports = measure.split((1,measure.shape[0]-1),0)[1].numpy()
    return [weights,supports]

#def gradient (weights,supports):
    #vec = np.sum(weights*supports,0)
    #return 2*np.dot(weights,vec)

S = Sphere(2)
MonS = MeasureSpace(S,1,"WFR",True)
print(MonS)
print(MonS._metric)
e = MonS.random(1,6,200)
print(e)
k = split_measure(e[0])
weights = k[0]
supports = k[1]
print(weights)
print(supports)
scipy.optimize.minimize(closure_functional, weights, method='L-BFGS-B', args=supports, bounds=scipy.optimize.Bounds(lb=0))

[tensor([[ 1.8206e+02,  1.0586e+02,  4.8804e+01,  7.5918e+01,  5.2754e+01,
          1.6861e+02],
        [ 2.6743e-01, -4.9865e-01, -9.1461e-01, -2.7977e-01,  7.0873e-01,
         -9.0285e-01],
        [-8.0638e-01,  5.5479e-01,  1.2931e-01, -2.1518e-02, -4.4806e-01,
          2.9650e-02],
        [-5.2747e-01,  6.6600e-01,  3.8309e-01, -9.5982e-01,  5.4492e-01,
         -4.2894e-01]])]
[[182.06277 105.85815  48.80364  75.91759  52.75414 168.61116]]
[[ 0.2674297  -0.4986499  -0.9146142  -0.27977404  0.7087317  -0.902845  ]
 [-0.8063849   0.5547878   0.12931237 -0.02151838 -0.44806257  0.02964985]
 [-0.52747     0.6660021   0.38309163 -0.9598247   0.5449214  -0.42894274]]


C:\Users\Dylan\AppData\Local\Temp\ipykernel_15640\1954661211.py:34: DeprecationWarning: Use of `minimize` with `x0.ndim != 1` is deprecated. Currently, singleton dimensions will be removed from `x0`, but an error will be raised in SciPy 1.11.0.
  scipy.optimize.minimize(closure_functional, weights, method='L-BFGS-B', args=supports, bounds=scipy.optimize.Bounds(lb=0))


  message: CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
  success: True
   status: 0
      fun: 190775.98
        x: [ 1.821e+02  1.059e+02  4.880e+01  7.592e+01  5.275e+01
             1.686e+02]
      nit: 0
      jac: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
             0.000e+00]
     nfev: 7
     njev: 1
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>