In [1]:
import os
os.chdir('..')
from bcmout.Sphere import Sphere
from bcmout.MeasureSpace import MeasureSpace
import torch
import numpy as np
import scipy

def closure_functional (weights, supports):
    """Define a functional representing how close to being closed the measure is"""
    vec = np.sum(weights[0]*supports,0)
    return np.inner(vec,vec)

def split_measure (measure):
    weights = measure.split((1,measure.shape[0]-1),0)[0].numpy()
    supports = measure.split((1,measure.shape[0]-1),0)[1].numpy()
    return [weights,supports]

#def gradient (weights,supports):
    #vec = np.sum(weights*supports,0)
    #return 2*np.dot(weights,vec)

S = Sphere(2)
MonS = MeasureSpace(S,1,"WFR",True)
print(MonS)
print(MonS._metric)
e = MonS.random(1,6,200)
print(e)
k = split_measure(e[0])
weights = k[0]
supports = k[1]
print(weights)
print(supports)
scipy.optimize.minimize(closure_functional, weights, method='BFGS', args=supports, bounds=scipy.optimize.Bounds(lb=0))

[tensor([[ 6.1642e+01,  2.7880e+01,  1.5420e+02,  1.4410e+02,  6.2358e+00,
          1.5718e+02],
        [ 9.4421e-01,  8.0383e-02,  4.8050e-01, -8.0885e-01, -4.1030e-01,
         -7.8731e-01],
        [-3.1835e-01,  2.1833e-01,  8.1530e-01,  4.1279e-01, -7.7537e-01,
         -3.8608e-01],
        [ 8.4423e-02, -9.7256e-01, -3.2312e-01, -4.1876e-01,  4.8006e-01,
         -4.8072e-01]])]
[[ 61.642242   27.880192  154.1969    144.09607     6.2357783 157.18245  ]]
[[ 0.9442051   0.08038256  0.4805005  -0.80885154 -0.41030124 -0.787308  ]
 [-0.31835434  0.21833275  0.81529826  0.41278952 -0.775369   -0.38607678]
 [ 0.08442272 -0.9725582  -0.32312214 -0.4187649   0.48005816 -0.4807191 ]]


C:\Users\Dylan\AppData\Local\Temp\ipykernel_23944\4080524740.py:34: DeprecationWarning: Use of `minimize` with `x0.ndim != 1` is deprecated. Currently, singleton dimensions will be removed from `x0`, but an error will be raised in SciPy 1.11.0.
  scipy.optimize.minimize(closure_functional, weights, method='BFGS', args=supports, bounds=scipy.optimize.Bounds(lb=0))
C:\Users\Dylan\AppData\Roaming\Python\Python38\site-packages\scipy\optimize\_minimize.py:569: RuntimeWarning: Method BFGS cannot handle bounds.
  warn('Method %s cannot handle bounds.' % method,


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 22048.309
        x: [ 6.164e+01  2.788e+01  1.542e+02  1.441e+02  6.236e+00
             1.572e+02]
      nit: 0
      jac: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
             0.000e+00]
 hess_inv: [[1 0 ... 0 0]
            [0 1 ... 0 0]
            ...
            [0 0 ... 1 0]
            [0 0 ... 0 1]]
     nfev: 7
     njev: 1